### ISSUE TITLE
Text Display

### ISSUE THREAD

**Issue by bhaveshk023** [kamval/WINSTAR-WFxx#1]
I am using W70M series TFT display. I am not able to display text using this library. I am able to display graphics, but having issue in displaying text.
Using following command :
WF70M.Text_Command(0,3,0,0,200,180,0x84B818,0xFFFFFF,"Hello");
Please help.

**Comment by kamval** [comment]
> I am using W70M series TFT display. I am not able to display text using this library. I am able to display graphics, but having issue in displaying text.
> Using following command :
> WF70M.Text_Command(0,3,0,0,200,180,0x84B818,0xFFFFFF,"Hello");
> Please help.

I have tested the code with WF57MTIBCDRGB. The command set is the same for the all WFxx series, so WF70 should perform pretty much the same. 
I am expecting that the problem might be in Text_Command function due to the size of Command_Buffer, it length needs to be calculated automatically, however, had no time to implement it yet. Could you please try to change the array size to e.g. 40 ? 
Check file -> "Winstar-WFxx.cpp", function -> "WFxx::Text_Command", array -> "WFxx_Command_Buffer[40]"

**Comment by bhaveshk023** [comment]
Thank you for your reply.
The problem is in the WFxx_Command_Buffer in text_command function. I have made changes into it and it is working properly now. I think in the Text_Command function in the instruction WFxx.write(WFxx_Command_Buffer,sizeof(WFxx_Command_Buffer)); has to be changed. Instead of sizeof(WFxx_Command_Buffer) it should be the actual size of the data we are sending on the uart.
